import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF',
    paddingTop: Platform.OS === 'android' ? 40 : 50,
    paddingBottom: 15,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  headerTitle: { 
    fontSize: 22, 
    fontWeight: '900', 
    color: '#0F1111' 
  },
  cancelText: {
    fontSize: 14,
    color: '#111',
    fontWeight: '500',
    letterSpacing: 0.5,
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
    backgroundColor: '#FFF',
  },
  stepIndicator: {
    alignItems: 'center',
    width: 90,
  },
  stepCircleContainer: {
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
    backgroundColor: '#FFF',
    zIndex: 2,
  },
  stepCircleChecked: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFF',
    borderWidth: 1.5,
    borderColor: '#008296',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleActive: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#008296',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepCircleActiveInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#008296',
  },
  stepCircleInactive: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#D5D9D9',
    backgroundColor: '#FFF',
  },
  stepLine: {
    position: 'absolute',
    top: 11,
    left: '50%',
    width: '100%',
    height: 1.5,
    backgroundColor: '#008296',
    zIndex: 1,
  },
  stepLineInactive: {
    position: 'absolute',
    top: 11,
    left: '50%',
    width: '100%',
    height: 1.5,
    backgroundColor: '#D5D9D9',
    zIndex: 1,
  },
  stepTextActive: {
    fontSize: 12,
    color: '#008296',
    fontWeight: '500',
  },
  stepTextInactive: {
    fontSize: 12,
    color: '#555',
  },
  content: {
    flex: 1,
    backgroundColor: '#FFF',
  },
  deliverySection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 16,
    borderBottomWidth: 4,
    borderBottomColor: '#F2F2F2',
  },
  deliveryTextContainer: {
    flex: 1,
    marginLeft: 12,
    marginRight: 8,
  },
  deliveryTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0F1111',
    marginBottom: 4,
  },
  deliverySubtitle: {
    fontSize: 14,
    color: '#0F1111',
    lineHeight: 20,
  },
  changeText: {
    color: '#007185',
    fontSize: 14,
    fontWeight: '500',
    marginTop: 2,
  },
  orderSummaryCard: {
    margin: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#D5D9D9',
    borderRadius: 8,
    backgroundColor: '#FFF',
    flexDirection: 'row',
  },
  orderSummaryTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F1111',
    marginBottom: 4,
  },
  orderSummaryPrice: {
    fontSize: 16,
    fontWeight: '700',
    color: '#B12704',
  },
  orderSummarySubtitle: {
    fontSize: 14,
    color: '#0F1111',
    lineHeight: 20,
  },
  sectionHeaderAmazon: {
    fontSize: 12,
    fontWeight: '700',
    color: '#555',
    marginLeft: 16,
    marginTop: 16,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  paymentCardGroup: {
    borderWidth: 1,
    borderColor: '#D5D9D9',
    borderRadius: 8,
    marginHorizontal: 16,
    backgroundColor: '#FFF',
    overflow: 'hidden',
  },
  paymentCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
  },
  paymentCardRowActive: {
    backgroundColor: '#F0F8FA',
  },
  paymentTitle: {
    fontSize: 15,
    color: '#0F1111',
    fontWeight: '500',
    marginBottom: 2,
  },
  paymentTitleActive: {
    fontWeight: '700',
  },
  paymentSubtitle: {
    fontSize: 13,
    color: '#555',
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#888',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioOuterActive: {
    borderColor: '#007185',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#007185',
  },
  badge: {
    backgroundColor: '#007185',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    alignSelf: 'flex-start',
    marginBottom: 4,
  },
  badgeText: {
    fontSize: 10,
    color: '#FFF',
    fontWeight: '700',
  },
  footer: {
    backgroundColor: '#FFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5E5E5',
    paddingBottom: Platform.OS === 'ios' ? 30 : 16,
  },
  confirmButton: {
    backgroundColor: '#FFD814',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 2,
  },
  confirmButtonText: {
    color: '#111',
    fontSize: 15,
    fontWeight: '600',
  }
});
