import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Platform.OS === 'android' ? 40 : 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
    backgroundColor: '#FFF',
  },
  amazonLogoText: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0F1111',
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: '#F2F2F2',
    paddingBottom: 30,
  },
  topSection: {
    backgroundColor: '#FFF',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#D5D9D9',
    marginBottom: 8,
  },
  successRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  successText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#067D62',
    marginLeft: 8,
  },
  confirmationText: {
    fontSize: 14,
    color: '#0F1111',
    lineHeight: 20,
    marginBottom: 12,
  },
  orderNumberText: {
    fontSize: 14,
    color: '#555',
    marginBottom: 12,
  },
  shippingLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F1111',
    marginBottom: 4,
  },
  shippingValue: {
    fontSize: 14,
    color: '#0F1111',
    lineHeight: 20,
  },
  amazonCard: {
    backgroundColor: '#FFF',
    padding: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#D5D9D9',
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F1111',
    marginBottom: 12,
  },
  itemCard: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  itemImage: {
    width: 70,
    height: 70,
    borderRadius: 4,
    backgroundColor: '#F9F9F9',
    marginRight: 12,
    resizeMode: 'cover',
  },
  itemDetails: {
    flex: 1,
  },
  itemName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#007185',
    marginBottom: 4,
  },
  itemSeller: {
    fontSize: 12,
    color: '#555',
    marginBottom: 2,
  },
  itemQuantity: {
    fontSize: 13,
    color: '#0F1111',
  },
  itemAmount: {
    fontSize: 14,
    fontWeight: '700',
    color: '#B12704',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 14,
    color: '#0F1111',
  },
  summaryValue: {
    fontSize: 14,
    color: '#0F1111',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#D5D9D9',
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F1111',
  },
  totalValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#B12704',
  },
  detailsTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0F1111',
    marginBottom: 4,
  },
  detailsValue: {
    fontSize: 14,
    color: '#0F1111',
    fontWeight: '500',
    marginBottom: 2,
  },
  detailsMeta: {
    fontSize: 13,
    color: '#555',
  },
  actionContainer: {
    backgroundColor: '#FFF',
    padding: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#D5D9D9',
    alignItems: 'center',
  },
  buttonAmazonYellow: {
    backgroundColor: '#FFD814',
    width: '100%',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 2,
  },
  buttonAmazonYellowText: {
    color: '#111',
    fontSize: 15,
    fontWeight: '600',
  },
  buttonAmazonWhite: {
    backgroundColor: '#FFF',
    width: '100%',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D5D9D9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 1,
  },
  buttonAmazonWhiteText: {
    color: '#0F1111',
    fontSize: 15,
    fontWeight: '500',
  },
});
