import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F7F9FC' },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFF',
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#1A1F36' },
  itemCard: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    position: 'relative',
    alignItems: 'flex-start',
  },
  itemImage: { width: 80, height: 80, borderRadius: 8 },
  itemDetails: { paddingRight: 76 },
  itemName: { fontSize: 16, fontWeight: '600', color: '#1A1F36', marginBottom: 4 },
  itemPrice: { fontSize: 16, fontWeight: '700', color: '#0052CC' },
  unavailableText: { color: '#FF3B30', fontSize: 12, marginTop: 4, fontWeight: '600' },
  itemActionsRow: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
  quantityControl: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#D6E4FF', borderRadius: 8, overflow: 'hidden' },
  quantityButton: { width: 32, height: 30, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F7F9FC' },
  quantityValue: { minWidth: 34, textAlign: 'center', fontSize: 14, fontWeight: '700', color: '#1A1F36' },
  secondaryActions: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
  textAction: { marginRight: 18 },
  textActionLabel: { color: '#0052CC', fontSize: 13, fontWeight: '600' },
  removeActionLabel: { color: '#DC2626', fontSize: 13, fontWeight: '600' },
  itemSummary: { position: 'absolute', top: 16, right: 12, alignItems: 'flex-end' },
  subtotalLabel: { fontSize: 11, color: '#697386', marginBottom: 2 },
  subtotalAmount: { fontSize: 17, fontWeight: '800', color: '#1A1F36' },
  savedSection: { marginTop: 18, paddingTop: 18, borderTopWidth: 1, borderTopColor: '#E2E8F0' },
  savedSectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  savedSectionTitle: { marginLeft: 8, fontSize: 18, fontWeight: '800', color: '#1A1F36' },
  savedCard: { flexDirection: 'row', backgroundColor: '#FFFFFF', borderRadius: 12, padding: 12, marginBottom: 10, borderWidth: 1, borderColor: '#E2E8F0' },
  savedImage: { width: 70, height: 70, borderRadius: 8, backgroundColor: '#F3F4F6' },
  savedDetails: { flex: 1, marginLeft: 12 },
  moveToCartButton: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', marginTop: 8, paddingHorizontal: 11, paddingVertical: 7, borderRadius: 7, backgroundColor: '#0052CC' },
  moveToCartText: { marginLeft: 5, color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmationModal: {
    width: '85%',
    maxWidth: 400,
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
  },
  removeConfirmationIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FEE2E2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  confirmationTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1F36',
    marginBottom: 8,
    textAlign: 'center',
  },
  confirmationMessage: {
    fontSize: 16,
    color: '#697386',
    marginBottom: 24,
    textAlign: 'center',
    lineHeight: 22,
  },
  confirmationActions: {
    width: '100%',
    flexDirection: 'row',
    gap: 12,
  },
  noButton: {
    flex: 1,
    backgroundColor: '#F0F5FF',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D6E4FF',
  },
  noButtonText: {
    color: '#0052CC',
    fontSize: 16,
    fontWeight: '600',
  },
  removeYesButton: {
    flex: 1,
    backgroundColor: '#DC2626',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  yesButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '600',
  },
  emptyContainer: { alignItems: 'center', marginTop: 100 },
  emptyText: { marginTop: 16, fontSize: 16, color: '#697386' },
  footer: {
    backgroundColor: '#FFF',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingBottom: 30,
  },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15 },
  totalLabel: { fontSize: 18, color: '#697386' },
  totalAmount: { fontSize: 24, fontWeight: '700', color: '#1A1F36' },
  checkoutBtn: {
    backgroundColor: '#0052CC',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  checkoutBtnText: { color: '#FFF', fontSize: 16, fontWeight: '700' }
});
