import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F7F9FC' },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24, backgroundColor: '#F7F9FC' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#FFF', paddingTop: 50, paddingBottom: 15, paddingHorizontal: 16, borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#1A1F36' },
  content: { padding: 16, paddingBottom: 32 },
  notificationBanner: { flexDirection: 'row', backgroundColor: '#F0F5FF', borderRadius: 12, padding: 14, marginBottom: 14, borderWidth: 1, borderColor: '#D6E4FF' },
  bannerText: { flex: 1, marginLeft: 10 },
  notificationTitle: { fontSize: 15, fontWeight: '700', color: '#1A1F36', marginBottom: 4 },
  notificationBody: { color: '#4F566B', fontSize: 13, lineHeight: 19 },
  statusCard: { backgroundColor: '#FFF', borderRadius: 12, padding: 16, marginBottom: 14, borderWidth: 1, borderColor: '#E2E8F0' },
  statusLabel: { color: '#697386', fontSize: 12, marginBottom: 8 },
  statusRow: { flexDirection: 'row', alignItems: 'center' },
  statusValue: { fontSize: 17, fontWeight: '800', marginLeft: 8 },
  card: { backgroundColor: '#FFF', borderRadius: 12, padding: 16, marginBottom: 14, borderWidth: 1, borderColor: '#E2E8F0' },
  cardTitle: { color: '#1A1F36', fontSize: 16, fontWeight: '800', marginBottom: 12 },
  itemRow: { flexDirection: 'row', alignItems: 'center' },
  itemImage: { width: 76, height: 76, borderRadius: 9, backgroundColor: '#F3F4F6' },
  itemInfo: { flex: 1, marginLeft: 12 },
  itemName: { color: '#1A1F36', fontSize: 16, fontWeight: '700', marginBottom: 6 },
  personName: { color: '#1A1F36', fontSize: 15, fontWeight: '700', marginBottom: 6 },
  detailText: { color: '#697386', fontSize: 14, lineHeight: 22 },
  detailLabel: { color: '#1A1F36', fontWeight: '700' },
  amount: { color: '#0052CC', fontSize: 17, fontWeight: '800', marginTop: 5 },
  errorText: { color: '#697386', textAlign: 'center', fontSize: 15, marginTop: 12, marginBottom: 20 },
  backButton: { backgroundColor: '#0052CC', borderRadius: 8, paddingHorizontal: 22, paddingVertical: 11 },
  backButtonText: { color: '#FFF', fontWeight: '700' },
});
